-- LeatherTrace-BD Online v3.0
-- Run this complete script once in Supabase Dashboard -> SQL Editor.
-- It creates the cloud database, individual identities, role/access metadata,
-- image and Excel storage buckets, views, and an atomic SHA-256 hash-linked ledger.

create extension if not exists pgcrypto;

create table if not exists public.app_users (
    id bigint generated by default as identity primary key,
    individual_user_id text not null unique,
    username text not null unique,
    full_name text not null,
    password_salt text not null,
    password_hash text not null,
    role text not null check (role in (
        'collector','tannery_intake','quality_inspector','environmental_officer',
        'tannery_processing','buyer','auditor','admin'
    )),
    role_code text not null,
    access_profile text not null,
    organisation text not null,
    active boolean not null default true,
    must_change_password boolean not null default true,
    password_changed_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.login_audit (
    id bigint generated by default as identity primary key,
    identity_entered text not null,
    individual_user_id text,
    success boolean not null,
    logged_at timestamptz not null default now()
);

create table if not exists public.source_receipts (
    id bigint generated by default as identity primary key,
    source_receipt_id text not null unique,
    created_by bigint references public.app_users(id),
    source_type text not null,
    source_region text not null,
    reference_status text not null,
    official_reference text,
    gps_lat double precision,
    gps_lon double precision,
    formatted_address text,
    google_place_id text,
    google_maps_url text,
    gps_capture_method text,
    slaughter_point_type text not null,
    preservation_method text not null,
    salting_delay_hours double precision not null,
    collection_timestamp text not null,
    notes text,
    row_version integer not null default 1,
    updated_at timestamptz not null default now(),
    updated_by bigint references public.app_users(id),
    created_at timestamptz not null default now()
);

create table if not exists public.batches (
    id bigint generated by default as identity primary key,
    batch_id text not null unique,
    source_receipt_id bigint not null references public.source_receipts(id),
    collector_user_id bigint references public.app_users(id),
    hide_count integer not null check (hide_count > 0),
    status text not null,
    tannery_received_by bigint references public.app_users(id),
    received_at timestamptz,
    row_version integer not null default 1,
    updated_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create table if not exists public.inspections (
    id bigint generated by default as identity primary key,
    inspection_id text not null unique,
    batch_id bigint not null references public.batches(id),
    image_storage_path text not null,
    original_filename text,
    image_sha256 text not null,
    image_uploaded_by bigint references public.app_users(id),
    image_uploaded_at timestamptz not null default now(),
    ai_mode text not null,
    detected_defects jsonb not null default '[]'::jsonb,
    defect_score double precision not null,
    defective_area_pct double precision not null,
    usable_area_pct double precision not null,
    ai_suggested_grade text not null check (ai_suggested_grade in ('A','B','C')),
    ai_confidence double precision not null,
    human_confirmed_grade text check (human_confirmed_grade in ('A','B','C')),
    override_reason text,
    inspector_user_id bigint references public.app_users(id),
    status text not null,
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    unique(batch_id)
);

create table if not exists public.tannery_intakes (
    id bigint generated by default as identity primary key,
    intake_id text not null unique,
    batch_id bigint not null unique references public.batches(id),
    receiving_user_id bigint references public.app_users(id),
    receiving_organisation text not null,
    received_at timestamptz not null,
    received_quantity integer not null,
    collector_image_verified boolean not null default false,
    ai_grade_seen text,
    intake_status text not null,
    notes text,
    row_version integer not null default 1,
    updated_at timestamptz not null default now()
);

create table if not exists public.environmental_records (
    id bigint generated by default as identity primary key,
    effluent_record_id text not null unique,
    production_shift_id text not null,
    sample_timestamp text not null,
    measurement_source text not null,
    ph double precision not null,
    "chromium_mgL" double precision not null,
    "bod_mgL" double precision not null,
    "cod_mgL" double precision not null,
    threshold_version text not null,
    compliance_status text not null check (compliance_status in ('PASS','FAIL')),
    entered_by bigint references public.app_users(id),
    created_at timestamptz not null default now()
);

create table if not exists public.processing_lots (
    id bigint generated by default as identity primary key,
    processing_lot_id text not null unique,
    batch_id bigint not null unique references public.batches(id),
    production_shift_id text not null,
    environmental_record_id bigint references public.environmental_records(id),
    process_stage text not null,
    process_start text not null,
    process_end text,
    output_area_sqft double precision,
    created_by bigint references public.app_users(id),
    created_at timestamptz not null default now()
);

create table if not exists public.decisions (
    id bigint generated by default as identity primary key,
    decision_id text not null unique,
    batch_id bigint not null unique references public.batches(id),
    final_decision text not null,
    payment_action text not null,
    quality_status text not null,
    environmental_status text not null,
    integrity_status text not null,
    reasons jsonb not null default '[]'::jsonb,
    created_by bigint references public.app_users(id),
    created_at timestamptz not null default now()
);

create table if not exists public.finished_lots (
    id bigint generated by default as identity primary key,
    finished_lot_id text not null unique,
    processing_lot_id bigint not null unique references public.processing_lots(id),
    traceability_qr_id text not null unique,
    destination_market text not null,
    buyer_reference text,
    status text not null,
    created_by bigint references public.app_users(id),
    created_at timestamptz not null default now()
);

create table if not exists public.excel_sync_log (
    id bigint generated by default as identity primary key,
    sync_direction text not null,
    status text not null,
    reason text,
    row_count integer,
    actor_user_id bigint references public.app_users(id),
    actor_individual_id text,
    error_report jsonb,
    synced_at timestamptz not null default now()
);

create table if not exists public.ledger_transactions (
    id bigint generated by default as identity primary key,
    transaction_id text not null unique,
    record_type text not null,
    related_batch_id text,
    actor_user_id bigint,
    actor_individual_id text,
    actor_role text not null,
    actor_org text not null,
    payload jsonb not null,
    previous_hash text not null,
    record_hash text not null,
    created_at timestamptz not null
);

create index if not exists idx_batches_status on public.batches(status);
create index if not exists idx_batches_collector on public.batches(collector_user_id);
create index if not exists idx_ledger_batch on public.ledger_transactions(related_batch_id);
create index if not exists idx_excel_sync on public.excel_sync_log(synced_at desc);

create or replace function public.append_ledger_transaction(
    p_transaction_id text,
    p_record_type text,
    p_related_batch_id text,
    p_actor_user_id bigint,
    p_actor_individual_id text,
    p_actor_role text,
    p_actor_org text,
    p_payload jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_previous_hash text;
    v_record_hash text;
    v_created_at timestamptz := clock_timestamp();
    v_canonical text;
    v_row public.ledger_transactions%rowtype;
begin
    perform pg_advisory_xact_lock(7823419901);
    select record_hash into v_previous_hash from public.ledger_transactions order by id desc limit 1;
    v_previous_hash := coalesce(v_previous_hash, repeat('0', 64));
    v_canonical := jsonb_build_object(
        'transaction_id', p_transaction_id,
        'record_type', p_record_type,
        'related_batch_id', p_related_batch_id,
        'actor_user_id', p_actor_user_id,
        'actor_individual_id', p_actor_individual_id,
        'actor_role', p_actor_role,
        'actor_org', p_actor_org,
        'payload', p_payload,
        'previous_hash', v_previous_hash,
        'created_at', v_created_at
    )::text;
    v_record_hash := encode(digest(v_canonical, 'sha256'), 'hex');
    insert into public.ledger_transactions(
        transaction_id, record_type, related_batch_id, actor_user_id,
        actor_individual_id, actor_role, actor_org, payload, previous_hash, record_hash, created_at
    ) values (
        p_transaction_id, p_record_type, p_related_batch_id, p_actor_user_id,
        p_actor_individual_id, p_actor_role, p_actor_org, p_payload, v_previous_hash, v_record_hash, v_created_at
    ) returning * into v_row;
    return to_jsonb(v_row);
end;
$$;

create or replace function public.verify_ledger()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    r public.ledger_transactions%rowtype;
    v_expected_previous text := repeat('0', 64);
    v_expected_hash text;
    v_canonical text;
    v_checked integer := 0;
begin
    for r in select * from public.ledger_transactions order by id loop
        if r.previous_hash <> v_expected_previous then
            return jsonb_build_object('valid', false, 'checked', v_checked, 'invalid_id', r.id,
                                      'message', 'Previous-hash linkage mismatch');
        end if;
        v_canonical := jsonb_build_object(
            'transaction_id', r.transaction_id,
            'record_type', r.record_type,
            'related_batch_id', r.related_batch_id,
            'actor_user_id', r.actor_user_id,
            'actor_individual_id', r.actor_individual_id,
            'actor_role', r.actor_role,
            'actor_org', r.actor_org,
            'payload', r.payload,
            'previous_hash', r.previous_hash,
            'created_at', r.created_at
        )::text;
        v_expected_hash := encode(digest(v_canonical, 'sha256'), 'hex');
        if r.record_hash <> v_expected_hash then
            return jsonb_build_object('valid', false, 'checked', v_checked, 'invalid_id', r.id,
                                      'message', 'Record hash mismatch');
        end if;
        v_expected_previous := r.record_hash;
        v_checked := v_checked + 1;
    end loop;
    return jsonb_build_object('valid', true, 'checked', v_checked, 'invalid_id', null,
                              'message', 'Ledger verified successfully');
end;
$$;

-- Views used by the application and the linked Excel workbook.
create or replace view public.source_batch_view as
select b.id, b.batch_id, b.collector_user_id, u.individual_user_id as collector_individual_id,
       u.organisation as collector_organisation, b.hide_count, b.status, b.row_version,
       b.created_at, b.updated_at,
       s.source_receipt_id, s.source_type, s.source_region, s.reference_status,
       s.official_reference, s.collection_timestamp, s.gps_lat, s.gps_lon,
       s.formatted_address, s.google_place_id, s.google_maps_url, s.gps_capture_method,
       s.slaughter_point_type, s.preservation_method, s.salting_delay_hours, s.notes,
       i.inspection_id, i.image_storage_path, i.original_filename, i.image_sha256,
       i.image_uploaded_at, i.ai_mode, i.detected_defects, i.defect_score,
       i.defective_area_pct, i.usable_area_pct, i.ai_suggested_grade, i.ai_confidence,
       i.human_confirmed_grade, i.status as inspection_status
from public.batches b
join public.source_receipts s on s.id=b.source_receipt_id
left join public.app_users u on u.id=b.collector_user_id
left join public.inspections i on i.batch_id=b.id;

create or replace view public.tannery_receive_view as
select * from public.source_batch_view;

create or replace view public.inspection_view as
select i.id, i.inspection_id, i.batch_id as batch_id_db, b.batch_id,
       i.image_storage_path, i.original_filename, i.image_sha256, i.image_uploaded_at,
       i.ai_mode, i.detected_defects, i.defect_score, i.defective_area_pct,
       i.usable_area_pct, i.ai_suggested_grade, i.ai_confidence,
       i.human_confirmed_grade, i.override_reason, i.status, i.created_at, i.reviewed_at,
       s.source_region, s.collection_timestamp, s.gps_lat, s.gps_lon, s.formatted_address
from public.inspections i
join public.batches b on b.id=i.batch_id
join public.source_receipts s on s.id=b.source_receipt_id;

create or replace view public.processing_candidate_view as
select b.id, b.batch_id, b.status, s.reference_status, s.salting_delay_hours,
       i.ai_suggested_grade, i.human_confirmed_grade, i.defect_score
from public.batches b
join public.source_receipts s on s.id=b.source_receipt_id
join public.inspections i on i.batch_id=b.id and i.status='CONFIRMED'
left join public.processing_lots p on p.batch_id=b.id
where p.id is null;

create or replace view public.processing_view as
select p.id, p.processing_lot_id, p.batch_id as batch_id_db, b.batch_id,
       p.production_shift_id, p.environmental_record_id, p.process_stage,
       p.process_start, p.process_end, p.output_area_sqft, p.created_at,
       e.effluent_record_id, e.compliance_status,
       d.decision_id, d.final_decision, d.payment_action, d.reasons
from public.processing_lots p
join public.batches b on b.id=p.batch_id
left join public.environmental_records e on e.id=p.environmental_record_id
left join public.decisions d on d.batch_id=p.batch_id;

create or replace view public.decision_view as
select d.id, d.decision_id, b.batch_id, d.final_decision, d.payment_action,
       d.quality_status, d.environmental_status, d.integrity_status,
       d.reasons, d.created_at
from public.decisions d join public.batches b on b.id=d.batch_id;

create or replace view public.traceability_view as
select f.id, f.finished_lot_id, f.traceability_qr_id, f.destination_market,
       f.buyer_reference, f.status as traceability_status, f.created_at,
       p.processing_lot_id, p.production_shift_id, p.process_stage,
       b.batch_id, s.source_type, s.source_region, s.collection_timestamp,
       s.gps_lat, s.gps_lon, s.formatted_address, s.google_maps_url,
       i.image_storage_path, i.image_sha256, i.image_uploaded_at,
       i.ai_suggested_grade, i.ai_confidence, i.human_confirmed_grade,
       e.compliance_status, d.final_decision, d.payment_action, d.integrity_status
from public.finished_lots f
join public.processing_lots p on p.id=f.processing_lot_id
join public.batches b on b.id=p.batch_id
join public.source_receipts s on s.id=b.source_receipt_id
join public.inspections i on i.batch_id=b.id
left join public.environmental_records e on e.id=p.environmental_record_id
left join public.decisions d on d.batch_id=b.id;

-- Demo individual accounts. Passwords are PBKDF2-HMAC-SHA256 hashes, never plaintext.
insert into public.app_users(
    individual_user_id,username,full_name,password_salt,password_hash,role,role_code,
    access_profile,organisation,active,must_change_password
) values
('CLT-DHK-0001','collector1','Demo Collector','725ef3f9ef606f06f75b293fe5347aca','229a5fa4d51068f3ea04c2cfd18d8f9fff954cacefea14d332844766283ab689','collector','CLT','COLLECTOR_STANDARD','Dhaka Hide Collectors',true,false),
('TAN-INT-0001','intake1','Demo Intake Officer','89b8d7d261eb80e1a2c183d66bba1c34','3e6712e16b25c12d3f693ec2e0864c54c05a4bae996486795b1d9a69aa5ccbca','tannery_intake','TAN-INT','TANNERY_INTAKE','Savar Tannery Estate',true,false),
('TAN-QA-0001','quality1','Demo Quality Inspector','03287d6b8ce95fa52ca627c2e1cb7b60','5bb569d3964b8e426ff5dcf672db7211397e3f6f85895616b1645ea1baca2d8a','quality_inspector','TAN-QA','QUALITY_CONTROL','Savar Tannery Estate',true,false),
('TAN-ENV-0001','env1','Demo Environmental Officer','ad024ecd81b92a9ef9c41f8f91e9e85c','267ab4d30b4e7123862846ec7297bb5eb8040503893299e4c275fa284e73f038','environmental_officer','TAN-ENV','ENVIRONMENTAL_DATA','Savar Tannery Estate',true,false),
('TAN-PRC-0001','process1','Demo Processing Officer','97ae1c065dd7e0d6206a949c336fb430','c1d57241aa23ffaaaf96ad6a4610414851c03fac409c9a7c58aed445242be167','tannery_processing','TAN-PRC','PROCESSING_CONTROL','Savar Tannery Estate',true,false),
('BUY-EXP-0001','buyer1','Demo Buyer','078d7f49bb0b3455f83200eb34b24fa1','d953ccead10bcd04778cb5946ad52ed3636550f6329226089c4a621f6a41e872','buyer','BUY','BUYER_READ_ONLY','International Buyer Demo',true,false),
('AUD-REG-0001','auditor1','Demo Auditor','15665386a13f137ed3ec8a7b4fc51813','e1e2f55db8c3d9d4aa7acb659bae09c2c5a272ae7973b016652cbb30fb54af16','auditor','AUD','AUDITOR_READ_ONLY','Compliance Audit Team',true,false),
('ADM-SYS-0001','admin','Demo Administrator','0d5f2f7f127446c15ada5f899a40a9da','89ccfdbad67f712e9865d889494a69cb14d25fec62b20c421bf6f440ce576139','admin','ADM','SYSTEM_ADMIN','LeatherTrace-BD',true,false)
on conflict (individual_user_id) do update set
username=excluded.username,full_name=excluded.full_name,password_salt=excluded.password_salt,
password_hash=excluded.password_hash,role=excluded.role,role_code=excluded.role_code,
access_profile=excluded.access_profile,organisation=excluded.organisation,active=true;

-- Private storage: images and the central linked Excel workbook.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('leather-images','leather-images',false,20971520,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=false,file_size_limit=20971520,
allowed_mime_types=array['image/jpeg','image/png','image/webp'];

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('system-files','system-files',false,52428800,
array['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv'])
on conflict (id) do update set public=false,file_size_limit=52428800,
allowed_mime_types=array['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','text/csv'];

-- The Streamlit server uses the server-side service/secret key. Direct browser access is denied.
alter table public.app_users enable row level security;
alter table public.login_audit enable row level security;
alter table public.source_receipts enable row level security;
alter table public.batches enable row level security;
alter table public.inspections enable row level security;
alter table public.tannery_intakes enable row level security;
alter table public.environmental_records enable row level security;
alter table public.processing_lots enable row level security;
alter table public.decisions enable row level security;
alter table public.finished_lots enable row level security;
alter table public.excel_sync_log enable row level security;
alter table public.ledger_transactions enable row level security;

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;
grant execute on function public.append_ledger_transaction(text,text,text,bigint,text,text,text,jsonb) to service_role;
grant execute on function public.verify_ledger() to service_role;
revoke all on all tables in schema public from anon, authenticated;
revoke execute on function public.append_ledger_transaction(text,text,text,bigint,text,text,text,jsonb) from anon, authenticated;
revoke execute on function public.verify_ledger() from anon, authenticated;
